apiVersion: v1
kind: Pod
metadata:
  name: scraper
  namespace: stocks2mars
spec:
  containers:
  - name: scraper-ctr
    image: stocks2mars/scraper
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
